[package]
name = "rdf-types"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
description = "Data-structures and traits definitions for RDF."
categories = ["data-structures"]
keywords = ["rdf", "w3c", "triple", "quad", "blank"]
repository = "https://github.com/timothee-haudebourg/rdf-types"
documentation = "https://docs.rs/rdf-types"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2021"
rust-version = "1.70.0"
version = "0.22.4"

[features]
serde = ["dep:serde"]

[dependencies]
# Major dependencies (major version must be synchronized).

thiserror = "1.0.57"
serde = { version = "1.0", features = ["derive"], optional = true }
uuid = { version = "0.8", optional = true }

# Minor dependencies.
indexmap = "2.2.5"
educe = "0.5.11"
slab = "0.4.9"
replace_with = "0.1.7"
raw-btree = "0.2.0"
futures-lite = "2.6.1"
into-owned-trait = "1.0.0"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
