[package]
name = "rdf-types"
authors = ["Timothée Haudebourg <author@haudebourg.net>"]
description = "Data-structures and traits definitions for RDF."
categories = ["data-structures"]
keywords = ["rdf", "w3c", "triple", "quad"]
repository = "https://github.com/timothee-haudebourg/rdf-types"
documentation = "https://docs.rs/rdf-types"
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2024"
rust-version = "1.85.0"
version = "1.0.0"

[features]
serde = ["dep:serde"]

[dependencies]
# Major dependencies (major version must be synchronized).
serde = { version = "1.0", features = ["derive"], optional = true }
into-owned-trait = "1.0.0"

# Minor dependencies.
educe = "0.5.11"
slab = "0.4.9"
replace_with = "0.1.7"
raw-btree = "0.2.0"
futures-lite = "2.6.1"

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
